#!/usr/bin/env python3
import sys

from pathlib import PurePath
from lib2to3.main import main

sys.path.append(PurePath(sys.argv[0]).parent)


if __name__ == '__main__':
    sys.exit(main('rose_fixers'))
